In [1]:
from zipfile import ZipFile
dataset = 'dogs-vs-cats.zip'

with ZipFile(dataset,'r') as zip:
    zip.extractall()
    print('The dataset is extracted')

The dataset is extracted


In [2]:
from zipfile import ZipFile
dataset = 'train.zip'

with ZipFile(dataset,'r') as zip:
    zip.extractall()
    print('The dataset is extracted')

KeyboardInterrupt: 

In [ ]:
import os
#counting the number of files in train folder
path, dirs, files = next(os.walk('train'))
file_count = len(files)
print('Number of images:', file_count)

In [ ]:
file_names = os.listdir('train')
print(file_names)

In [6]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn.model_selection import train_test_split
import cv2

In [ ]:
#display dog image
img = mpimg.imread('train/cat.1000.jpg')
imgplt = plt.imshow(img)
plt.show

In [ ]:
file_names = os.listdir('train')

for i in range(len(file_names)):
    name = file_names[i]
    print(name[0:3])

In [ ]:
file_names = os.listdir('train')

dog_count = 0
cat_count = 0

for img_file in file_names:
    
    name = img_file[0:3]
    
    if name == 'dog':
        dog_count +=1
    else:
        cat_count +=1

print('Number of dog images =', dog_count)
print('Number of cat images =', cat_count)
    

In [ ]:
# creating directory for resized images
os.mkdir('image_resized_3')

In [ ]:
original_folder = 'image_resized'
resized_folder = 'image_resized_3'

for i in range(2014):
    
    file_name = os.listdir(original_folder)[i]
    img_path = original_folder+'/'+file_name
    
    img = Image.open(img_path)
    img = img.resize((224, 224))
    img = img.convert('RGB')
    
    newImgPath = resized_folder+'/'+file_name
    img.save(newImgPath)

In [ ]:
img = mpimg.imread('image_resized_3/cat.0.jpg')
imgplt = plt.imshow(img)
plt.show

In [8]:
import os
# creating labels for resized images
file_names = os.listdir('image_resized_3')
labels = []

for i in range(2014):
    
    file_name = file_names[i]
    label = file_name[0:3]
    
    if label == 'dog':
        labels.append(1) # Dog
    else:
        labels.append(0) # Cat

In [9]:
print(file_names[0:5])
print(len(file_names))

['cat.0.jpg', 'cat.1.jpg', 'cat.10.jpg', 'cat.100.jpg', 'cat.1000.jpg']
2014


In [10]:
print(labels[:5])
print(len(labels))

[0, 0, 0, 0, 0]
2014


In [11]:
print(labels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [12]:
#counting the images of dogs and cats out of 2014
values, counts = np.unique(labels, return_counts=True)
print(values)
print(counts)

[0 1]
[1008 1006]


In [13]:
#Converting all the resized images to numpy array
import cv2
import glob

In [14]:
image_directory = 'image_resized_3/'
image_extension = ['png', 'jpg']

files = []

[files.extend(glob.glob(image_directory + '*.' + e)) for e in image_extension]
dog_cat_images = np.asarray([cv2.imread(file) for file in files])

In [15]:
print(dog_cat_images)

[[[[ 87 163 205]
   [ 89 165 207]
   [ 92 168 210]
   ...
   [125 203 246]
   [123 200 246]
   [123 200 246]]

  [[ 87 163 205]
   [ 89 165 207]
   [ 92 168 210]
   ...
   [125 203 246]
   [124 201 247]
   [123 200 246]]

  [[ 87 163 205]
   [ 89 165 207]
   [ 92 168 210]
   ...
   [125 203 246]
   [124 201 247]
   [124 201 247]]

  ...

  [[ 57 123 158]
   [ 57 123 158]
   [ 56 124 159]
   ...
   [  0   2   1]
   [  0   2   1]
   [  0   2   1]]

  [[ 55 121 156]
   [ 56 122 157]
   [ 55 123 158]
   ...
   [  0   2   1]
   [  0   2   1]
   [  0   2   1]]

  [[ 54 120 155]
   [ 54 120 155]
   [ 53 121 156]
   ...
   [  0   2   1]
   [  0   2   1]
   [  0   2   1]]]


 [[[ 43  43  37]
   [ 47  47  41]
   [ 47  47  41]
   ...
   [181 207 207]
   [169 199 200]
   [161 194 197]]

  [[ 42  42  36]
   [ 46  46  40]
   [ 45  45  39]
   ...
   [176 202 202]
   [167 196 200]
   [164 197 200]]

  [[ 42  42  36]
   [ 44  44  38]
   [ 43  43  37]
   ...
   [168 194 194]
   [165 194 198]
   [168 200

In [16]:
type(dog_cat_images)

numpy.ndarray

In [17]:
print(dog_cat_images.shape)

(2014, 224, 224, 3)


In [18]:
X = dog_cat_images
Y = np.asarray(labels)

In [19]:
# Train Test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [20]:
print(X.shape, X_train.shape, X_test.shape) # 8000 training images, 2000 test images

(2014, 224, 224, 3) (1611, 224, 224, 3) (403, 224, 224, 3)


In [21]:
# scaling the data
X_train_scaled = X_train/255

X_test_scaled = X_test/255

In [22]:
print(X_train_scaled)

[[[[0.31764706 0.18823529 0.29411765]
   [0.31372549 0.19215686 0.29803922]
   [0.33333333 0.21176471 0.3254902 ]
   ...
   [0.1372549  0.05098039 0.27843137]
   [0.1254902  0.03529412 0.27843137]
   [0.10588235 0.02352941 0.26666667]]

  [[0.29803922 0.16862745 0.2745098 ]
   [0.3254902  0.20392157 0.30980392]
   [0.3372549  0.21568627 0.32941176]
   ...
   [0.1372549  0.04313725 0.27058824]
   [0.1254902  0.03921569 0.27058824]
   [0.10980392 0.03137255 0.2627451 ]]

  [[0.30980392 0.18039216 0.28627451]
   [0.35686275 0.23529412 0.34117647]
   [0.36862745 0.24705882 0.36078431]
   ...
   [0.1254902  0.03529412 0.24705882]
   [0.1254902  0.03529412 0.25098039]
   [0.12156863 0.03921569 0.25490196]]

  ...

  [[0.56078431 0.49803922 0.45098039]
   [0.59215686 0.52941176 0.48235294]
   [0.56862745 0.50980392 0.4745098 ]
   ...
   [0.09803922 0.06666667 0.06666667]
   [0.09411765 0.0627451  0.0627451 ]
   [0.08627451 0.05490196 0.05490196]]

  [[0.55294118 0.49019608 0.44313725]
   [0.5

In [23]:
import tensorflow as tf
import tensorflow_hub as hub


In [24]:
mobilenet_model = 'https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4'

pretrained_model = hub.KerasLayer(mobilenet_model, input_shape = (224,224, 3), trainable=False)

In [25]:
num_of_classes = 2
model = tf.keras.Sequential([
    pretrained_model, 
    tf.keras.layers.Dense(num_of_classes)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 1280)              2257984   
                                                                 
 dense (Dense)               (None, 2)                 2562      
                                                                 
Total params: 2260546 (8.62 MB)
Trainable params: 2562 (10.01 KB)
Non-trainable params: 2257984 (8.61 MB)
_________________________________________________________________


In [26]:
model.compile(
    optimizer='adam',
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ['acc']
)

In [27]:
model.fit(X_train_scaled, Y_train, epochs=5)

Epoch 1/5
51/51 [==============================] - 44s 746ms/step - loss: 0.1686 - acc: 0.9342
Epoch 2/5
51/51 [==============================] - 36s 704ms/step - loss: 0.0598 - acc: 0.9820
Epoch 3/5
51/51 [==============================] - 38s 734ms/step - loss: 0.0456 - acc: 0.9870
Epoch 4/5
51/51 [==============================] - 37s 733ms/step - loss: 0.0342 - acc: 0.9913
Epoch 5/5
51/51 [==============================] - 38s 741ms/step - loss: 0.0255 - acc: 0.9950


In [28]:
score, acc = model.evaluate(X_test_scaled, Y_test)
print('Test loss =', score)
print('Test accuracy =', acc)

13/13 [==============================] - 13s 821ms/step - loss: 0.0882 - acc: 0.9653
Test loss = 0.08818940818309784
Test accuracy = 0.9652605652809143


In [1]:
# Predictive system
input_image_path = input('Path of the image to be predicted: ')
input_image = cv2.imread(input_image_path)

cv2.imshow('',input_image)
cv2.waitkey(0)

input_image_resize = cv2.resize(input_image, (224, 224))

input_image_scaled = input_image_resize/255

image_reshaped = np.reshape(input_image_scaled, [1, 224, 224, 3])

input_prediction = model.predict(image_reshaped)

input_pred_label = np.argmax(input_prediction)

if input_pred_label == 0:
    print('The image represents a Cat')
else:
    print('The image represents a Dog')

Path of the image to be predicted: dog.jpg


NameError: name 'cv2' is not defined